TEXTS = {
    'ar': {
        'welcome': " أهلاً بك في **One Royal AI Trading**\nالرجاء اختيار اللغة الخاصة بك:",
        'lang_selected': " تم اختيار اللغة العربية بنجاح.",
        'enter_username': " أدخل اسم المستخدم (Username) الخاص بك للتسجيل:",
        'enter_password': " ادخل كلمة المرور الخاصة بك:",
        'registration_complete': " تم إنشاء حسابك بنجاح!\n\n**حالة الحساب:** غير مفعل.\nلتفعيل الحساب يلزم دفع 25$ رسوم التفعيل لأول مرة عبر قسم الإيداع.",
        'main_menu': " **القائمة الرئيسية**",
        'btn_profile': " الملف الشخصي",
        'btn_balance': " الرصيد",
        'btn_deposit': " الإيداع",
        'btn_withdraw': " ATM السحب",
        'btn_transactions': " سجل العمليات",
        'btn_settings': " الإعدادات",
        'btn_support': " الدعم",
        'account_inactive_warning': " **حسابك غير مفعل**\nيرجى إيداع رسوم التفعيل (25$) ليتم تفعيل حسابك من قبل الإدارة.",
        'profile_info': " **الملف الشخصي**\nID المعرف: {tg_id}\nاسم المستخدم: {username}\nاللغة: العربية\nحالة الحساب: {status}\nالرصيد الحالي: ${balance:.2f}\nتاريخ الإنشاء: {created_date}",
        'deposit_select': " **اختر طريقة الإيداع:**",
        'deposit_amount': " أدخل المبلغ المراد إيداعه بالدولار ($):\n*(ملاحظة: إذا كانت هذه أول عملية، فإن أول 25$ ستخصص لتفعيل الحساب)*",
        'deposit_sent': " تم إرسال طلب الإيداع بقيمة ${amount} إلى الإدارة للمراجعة والتأكيد.",
        'withdraw_amount': " أدخل المبلغ المراد سحبه بالدولار ($):",
        'withdraw_method': " أدخل طريقة السحب والعنوان / المعلومات التفصيلية:",
        'withdraw_sent': " تم إرسال طلب السحب إلى الإدارة للمراجعة.",
        'insufficient_balance': " رصيدك غير كافي لإجراء هذه العملية.",
        'support_msg': " **الدعم الفني**\nللتواصل المباشر مع الدعم الفني والإدارة: @OneRoyalSupport",
        'admin_only': " هذا الأمر مخصص للإدارة فقط."
    },
    'en': {
        'welcome': " Welcome to **One Royal AI Trading**\nPlease select your language:",
        'lang_selected': " English language selected successfully.",
        'enter_username': " Enter your username to register:",
        'enter_password': " Enter your password:",
        'registration_complete': " Account created successfully!\n\n**Account Status: Inactive.**\nTo activate your account, a **$25 initial activation fee** is required via Deposit.",
        'main_menu': " **Main Menu**",
        'btn_profile': " Profile",
        'btn_balance': " Balance",
        'btn_deposit': " Deposit",
        'btn_withdraw': " ATM Withdraw",
        'btn_transactions': " Transactions",
        'btn_settings': " Settings",
        'btn_support': " Support",
        'account_inactive_warning': " **Account is Inactive!**\nPlease deposit the $25 activation fee to get your account activated by admin.",
        'profile_info': " **User Profile**\nID: {tg_id}\nUsername: {username}\nLanguage: English\nAccount Status: {status}\nCurrent Balance: ${balance:.2f}\nCreated Date: {created_date}",
        'deposit_select': " **Select Payment Method:**",
        'deposit_amount': " Enter the amount you wish to deposit in USD ($):\n*(Note: If this is your first deposit, $25 will go towards account activation)*",
        'deposit_sent': " Deposit request of ${amount} submitted to management for verification.",
        'withdraw_amount': " Enter the amount you wish to withdraw in USD ($):",
        'withdraw_method': " Enter withdrawal method and payment address/details:",
        'withdraw_sent': " Withdrawal request submitted to management for approval.",
        'insufficient_balance': " Insufficient balance for this transaction.",
        'support_msg': " **Technical Support**\nFor support and inquiries, contact: @OneRoyalSupport",
        'admin_only': " This command is restricted to admins only."
    }
}
